import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import {ColorSchemeScript, MantineProvider, mantineHtmlProps} from '@mantine/core';
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import FormModal from "@/components/ui/modal/form.modal";
import MobileFormModal from "@/components/ui/modal/mobile-form.modal";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Helplly",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps}>
        <head>
            <title>Helplly</title>
            <ColorSchemeScript/>
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <MantineProvider>
            <Header/>
            <main className="container pt-[101px] lg:pt-[104px] mx-auto">
                {children}
            </main>
            <Footer/>
            <div className={'hidden sm:block'}>
                <FormModal/>
            </div>
            <div className={'block sm:hidden'}>
                <MobileFormModal/>
            </div>
        </MantineProvider>
        </body>
        </html>
    );
}
