import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import {ColorSchemeScript, MantineProvider, mantineHtmlProps} from '@mantine/core';
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import FormModal from "@/components/ui/modal/form.modal";
import MobileFormModal from "@/components/ui/modal/mobile-form.modal";
import NotificationsProvider from "@/components/notifications";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Helplly",
    description: "Generated by create next app",
    icons: {
        icon: "/icons/fav-icon.png",
    },
};


export default async function LocaleLayout({
                                               children,
                                               params
                                           }: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;
    const messages = await getMessages({ locale });
    return (
        <html lang={locale} {...mantineHtmlProps}>
        <head>
            <title>Helplly</title>
            <ColorSchemeScript/>
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <NextIntlClientProvider messages={messages}>
            <MantineProvider>
                <NotificationsProvider  />
                {await Header()}
                <main className=" pt-[101px] lg:pt-[114px] ">
                    {children}
                </main>
                <Footer/>
                <div className={'hidden sm:block'}>
                    <FormModal/>
                </div>
                <div className={'block sm:hidden'}>
                    <MobileFormModal/>
                </div>
            </MantineProvider>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
